### ISSUE TITLE
Web Assembly?

### ISSUE THREAD

**Issue by nemilya** [samuel-cavalcanti/rust_zmqRemoteApi#3]
Is it possible to porting this version to web-assembly, and by web-socket to communicate with CoppeliaSim from browser?

**Comment by samuel-cavalcanti** [comment]
Right now it is not possible to compile to wasi, because  the [zmq](https://crates.io/crates/zmq) crate doesn't support WebAssembly yet. For more information see this issue: <https://github.com/erickt/rust-zmq/issues/258>.

But it is possible  to communicate with CoppeliaSim from browser thought the  <https://github.com/CoppeliaRobotics/wsRemoteApi/>
